swsoyee/psnine-enhanced-version

- package.json
- psnineplus.js
根据issue https://github.com/swsoyee/psnine-enhanced-version/issues/54 的提议重新实现了pr https://github.com/swsoyee/psnine-enhanced-version/pull/43 ；另外refactor了一下2433～2446行。
绝大多数页面夜间模式都不会闪了，但是目前测试发现URL为`https://psnine.com/psngame/<gameid>`的页面还是会闪一下，但加上PSN ID之后的`https://psnine.com/psngame/<gameid>?psnid=<psnid>`又不会闪，可能跟css有关，@swsoyee 需要麻烦你调查一下了。
> [fix] insert dark mode css on document start

- package.json
- psnineplus.js
#69 理论上原来是刮刮卡的内容，在回复中依然显示成刮刮卡最好。
但是因为还有45个字的省略条件，以及鼠标悬浮显示全部内容，导致了边界条件判断起来很困难。
本人不是专业前端 JS 水平又差，只能先用这种替换方式，让用户直接去看原内容剧透比较好。
> 机因中显示被@的内容的时候保持刮刮卡显示

- psnineplus.js
P9更新了二级回复显示顺序，现在reverseSubReply()反而会把顺序变成时间倒序
> [chore] disabled reverseSubReply(), no longer required

- package.json
- psnineplus.js
注意到虽然之前QA页面的二级回复改成顺序了，但奖杯TIPS和个人主页留言还是倒序的
> [chore] re-enable reverseSubReply() on some pages

- psnineplus.js
> [fix] open detected plain text links in new tabs

- package-lock.json
- package.json
- psnineplus.js
问答的标题比较长、需要占用两行及以上的时候，状态标志会跟最后一行对齐。
Before:
After:
> [fix] misplaced QA status icons

- package-lock.json
- package.json
- psnineplus.js
最近P9后台改动的缺陷导致HTTPS页面在大部分浏览器的默认安全策略下都不能正常显示，反馈了近一周了也没改，先自己强行修复一下。
> Fix the issue where http resources are used on https pages

- .gitignore
- package-lock.json
- package.json
- psnineplus.js
script置换之后，部分元素的onlick()不能立刻使用；测试页面：[https://psnine.com/psngame/21725/comment](https://psnine.com/psngame/21725/comment)、[https://psnine.com/qa/36145](https://psnine.com/qa/36145)、[https://psnine.com/trophy/20004004](https://psnine.com/trophy/20004004)
css置换之后，Highcharts绘制的图表出现显示问题；测试页面：[https://psnine.com/psngame/11631](https://psnine.com/psngame/11631)、[https://psnine.com/psngame/11631/comment](https://psnine.com/psngame/11631/comment)
> More HTTPS-related fixes

- package-lock.json
- package.json
- psnineplus.js
1. 某些老游戏页面评论时间戳解析不正确。（例：[https://psnine.com/psngame/4712/comment](https://psnine.com/psngame/4712/comment)）
2. Highcharts新版本在一定条件下生成的图表Y轴tick过于密集。（例：[https://psnine.com/psngame/20919/comment](https://psnine.com/psngame/20919/comment)、[https://www.psnine.com/psngame/16758/comment](https://www.psnine.com/psngame/16758/comment)）
> 修复评论分数趋势图相关问题

- package-lock.json
- package.json
- psnineplus.js
注意到比较老的游戏的评论页面并非使用层内回复，有必要打开replyTraceback。
测试页面：[https://psnine.com/psngame/3001/comment](https://psnine.com/psngame/3001/comment), [https://psnine.com/psngame/5254/comment](https://psnine.com/psngame/5254/comment)
> [fix] enable replyTraceback on game comment pages

- package-lock.json
- package.json
- psnineplus.js
1. 修复部分游戏评论页面其他版本信息显示位置不正确的问题。
2. 因部分游戏P9管理员没有关联其他版本，重新设计了两种查询方式的互补方式以尽可能找到游戏的不同版本。
均以[《祭物与雪之刹那》](https://psnine.com/psngame/10282)为例。
> [fix] style adjusment; improved game variant lookup procedure

- package-lock.json
- package.json
- psnineplus.js
1. 改进游戏多版本引用与暗黑模式的兼容性，使用原生的box class代替硬编码的背景颜色值，使其可以动态改变。
2. 改进奖杯Tips按赞排序功能在旧版奖杯页面下的兼容性。例：https://psnine.com/trophy/3761001
> [fix] compatibility fixes

- package-lock.json
- package.json
- psnineplus.js
[《对马岛之魂》](https://psnine.com/psngame/22859)新增了PSPC平台，临时修复平台图标显示。
> [fix] temporarily fix PSPC icon style until PSNINE officially does so.

- package-lock.json
- package.json
- psnineplus.js
最新版本的highcharts不知道是改了什么，会导致只有一个评分时游戏评分图表无法正常显示。回退到最后一个没有问题的版本。
测试页面：https://psnine.com/psngame/29843/comment
> [fix] freeze highcharts version to prevent a game score chart bug

- package.json
- psnineplus.js
在游列上添加个人游戏完成度的背景染色，效果如尾图：
代码中添加了两部分，
一部分是在个人页面更新游戏完成数据并添加到 GM_setValue 中的 savePersonalGameCompletions() 函数，该函数添加到了两处触发位置。
第二部分是在游戏列表中读取已保存数据并为对应游戏染底色。
其它行的变动为代码编辑器自行调整的缩进，我不知道怎么处理。// Update: lint used.
> 添加  “在游戏列表中为自己100%完成的游戏添加背景色” 功能

- package.json
- psnineplus.js
功能一：在约战页面添加了非 100% 游戏的奖杯进度背景进度条，与游列逻辑基本一致。
功能二：约战监测
1. 在游戏的约战页添加约战监测按钮。
2. 当其它用户发起该游戏的约战邀请时，在顶部菜单栏显示红点通知。
3. 通过 ajax 更新约战页列表，由于目前只有一页，不确定存在多页时的更新办法。
4. 设置了 update interval 为一小时，在 settings 中添加了配置项，但没有提供给用户的编辑页面，也不打算提供。
> 添加约战监控功能，以及在约战页显示非 100% 游戏的背景进度条

- package-lock.json
- package.json
- psnineplus.js
搜索列表：[https://psnine.com/psngame?title=蜘蛛侠](https://psnine.com/psngame?title=%E8%9C%98%E8%9B%9B%E4%BE%A0)
psngame页面：https://psnine.com/psngame/23378
topic页面的关联奖杯：https://psnine.com/topic/37655
游列：https://psnine.com/topic/38125
PS5 / PSPC：https://psnine.com/game/23378
仅PS5：https://psnine.com/game/34992
PS4 & PS5 (PS4在前)：https://psnine.com/game/37983
PS4 & PS5 (PS5在前)：https://psnine.com/game/11382
> [fix] 修复大部分页面的PSPC封面样式和game页面的PS5封面样式

- psnineplus.js
页面自动加载后修复PSPC封面样式；奖杯列表内的本体/DLC图标样式修复。
> [fix] 修复更多页面的PSPC封面样式

- package-lock.json
- package.json
- psnineplus.js
之前有bug的版本只会展开页面中一开始就能看到的二级评论区中的第一个，其它的只有在滚动出画面并再次滚动进画面一次之后才会展开，现已修复此问题。
测试页面：https://psnine.com/psngame/43387/comment
> [fix] 修复一个导致部分二级评论区未被展开的bug

- psnineplus.js
将PSPC图标的修正方式从`attr('height', '91')`改为`removeAttr('height')`，如未来P9站方修改封面的显示宽度，此脚本应该不用修改；此修改同时规避了topic的“关联奖杯”区域里PS4奖杯图标跟随PS5/PSPC图标一起被修改显示高度的错误（测试：[https://psnine.com/topic/37213](https://psnine.com/topic/37213)）
修改游戏评论区二级评论载入按钮的获取方式，less verbose & more robust
> Improved robustness
